import { Athlete, NewsItem } from './types';

// Generate realistic price history
const generatePriceHistory = (basePrice: number, volatility: number = 0.1) => {
  const history = [];
  let price = basePrice * 0.8; // Start 20% lower
  
  for (let i = 0; i < 30; i++) {
    const change = (Math.random() - 0.5) * volatility * price;
    price = Math.max(price + change, basePrice * 0.5);
    history.push({
      time: new Date(Date.now() - (29 - i) * 24 * 60 * 60 * 1000).toISOString(),
      price: Math.round(price * 100) / 100,
      volume: Math.floor(Math.random() * 50000) + 10000
    });
  }
  
  return history;
};

export const initialAthletes: Athlete[] = [
  {
    id: '1',
    name: 'Marco Silva',
    symbol: 'MSIL',
    sport: 'Football',
    category: 'Pro',
    nationality: 'Portugal',
    team: 'FC Porto',
    position: 'Midfielder',
    age: 24,
    height: '1.78m',
    bio: 'Dynamic midfielder with exceptional vision and passing ability. Started his career in the Portuguese youth leagues and quickly rose through the ranks. Known for his creative playmaking and ability to control the tempo of the game.',
    profileUrl: 'https://example.com/marco-silva',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=12',
    currentPrice: 250,
    price24hChange: 5.2,
    price7dChange: 12.8,
    tradingVolume: 125000,
    holders: 342,
    tags: ['Featured', 'Fast Growing'],
    priceHistory: generatePriceHistory(250),
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '2',
    name: 'Yuki Tanaka',
    symbol: 'YTAN',
    sport: 'Swimming',
    category: 'Elite',
    nationality: 'Japan',
    team: 'Tokyo Aquatics',
    position: 'Freestyle',
    age: 22,
    height: '1.85m',
    bio: 'Olympic gold medalist in 200m freestyle. Breaking records since junior competitions. Known for explosive speed and technical perfection in the water.',
    profileUrl: 'https://example.com/yuki-tanaka',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=33',
    currentPrice: 850,
    price24hChange: 8.5,
    price7dChange: 22.3,
    tradingVolume: 450000,
    holders: 892,
    tags: ['Featured', 'Elite'],
    priceHistory: generatePriceHistory(850),
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '3',
    name: 'Sofia Rodriguez',
    symbol: 'SROD',
    sport: 'Tennis',
    category: 'Pro',
    nationality: 'Spain',
    team: 'Independent',
    position: 'Singles',
    age: 21,
    height: '1.70m',
    bio: 'Rising star in women\'s tennis with powerful serves and aggressive baseline play. Winner of multiple ITF tournaments and climbing the WTA rankings rapidly.',
    profileUrl: 'https://example.com/sofia-rodriguez',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=45',
    currentPrice: 320,
    price24hChange: 3.8,
    price7dChange: 15.2,
    tradingVolume: 180000,
    holders: 456,
    tags: ['Fast Growing'],
    priceHistory: generatePriceHistory(320),
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '4',
    name: 'James Mitchell',
    symbol: 'JMIT',
    sport: 'Basketball',
    category: 'Semi-pro',
    nationality: 'USA',
    team: 'G League Warriors',
    position: 'Point Guard',
    age: 23,
    height: '1.88m',
    bio: 'Talented point guard with excellent court vision and three-point shooting. Working his way up through the G League with sights set on the NBA.',
    profileUrl: 'https://example.com/james-mitchell',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=15',
    currentPrice: 180,
    price24hChange: 2.1,
    price7dChange: 8.5,
    tradingVolume: 95000,
    holders: 234,
    tags: ['Promoted'],
    priceHistory: generatePriceHistory(180),
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '5',
    name: 'Amara Okafor',
    symbol: 'AOKA',
    sport: 'Athletics',
    category: 'Pro',
    nationality: 'Nigeria',
    team: 'Lagos Track Club',
    position: '100m Sprint',
    age: 25,
    height: '1.75m',
    bio: 'Explosive sprinter with sub-10 second 100m times. African champion and Olympic qualifier. Known for powerful starts and acceleration.',
    profileUrl: 'https://example.com/amara-okafor',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=28',
    currentPrice: 420,
    price24hChange: 6.7,
    price7dChange: 18.9,
    tradingVolume: 235000,
    holders: 567,
    tags: ['Featured'],
    priceHistory: generatePriceHistory(420),
    createdAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '6',
    name: 'Chen Wei',
    symbol: 'CWEI',
    sport: 'Table Tennis',
    category: 'Elite',
    nationality: 'China',
    team: 'Beijing TT',
    position: 'Singles/Doubles',
    age: 26,
    height: '1.73m',
    bio: 'World champion in table tennis with incredible reflexes and spin control. Multiple Olympic medals and dominates international competitions.',
    profileUrl: 'https://example.com/chen-wei',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=51',
    currentPrice: 680,
    price24hChange: 4.2,
    price7dChange: 11.5,
    tradingVolume: 380000,
    holders: 723,
    tags: ['Elite'],
    priceHistory: generatePriceHistory(680),
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '7',
    name: 'Emma Larsson',
    symbol: 'ELAR',
    sport: 'Gymnastics',
    category: 'Pro',
    nationality: 'Sweden',
    team: 'Stockholm Gymnastics',
    position: 'All-Around',
    age: 19,
    height: '1.58m',
    bio: 'Graceful gymnast with exceptional balance beam and floor routines. European championship medalist with Olympic aspirations.',
    profileUrl: 'https://example.com/emma-larsson',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=47',
    currentPrice: 290,
    price24hChange: 7.3,
    price7dChange: 20.1,
    tradingVolume: 165000,
    holders: 412,
    tags: ['Fast Growing', 'New'],
    priceHistory: generatePriceHistory(290),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '8',
    name: 'Diego Mendez',
    symbol: 'DMEN',
    sport: 'Boxing',
    category: 'Semi-pro',
    nationality: 'Mexico',
    team: 'Guadalajara Boxing',
    position: 'Welterweight',
    age: 24,
    height: '1.76m',
    bio: 'Aggressive boxer with a strong jab and excellent footwork. Undefeated in last 15 fights and targeting professional championship belts.',
    profileUrl: 'https://example.com/diego-mendez',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=13',
    currentPrice: 155,
    price24hChange: 1.8,
    price7dChange: 5.4,
    tradingVolume: 78000,
    holders: 198,
    tags: [],
    priceHistory: generatePriceHistory(155),
    createdAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '9',
    name: 'Léa Dubois',
    symbol: 'LDUB',
    sport: 'Fencing',
    category: 'Pro',
    nationality: 'France',
    team: 'Paris Fencing',
    position: 'Épée',
    age: 23,
    height: '1.72m',
    bio: 'Tactical fencer with lightning-fast reactions. French national champion and World Cup competitor with precise technique.',
    profileUrl: 'https://example.com/lea-dubois',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=26',
    currentPrice: 195,
    price24hChange: -1.2,
    price7dChange: 3.7,
    tradingVolume: 92000,
    holders: 267,
    tags: [],
    priceHistory: generatePriceHistory(195),
    createdAt: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '10',
    name: 'Kwame Mensah',
    symbol: 'KMEN',
    sport: 'Judo',
    category: 'Amateur',
    nationality: 'Ghana',
    team: 'Accra Judo',
    position: 'Under 73kg',
    age: 20,
    height: '1.70m',
    bio: 'Promising judoka with powerful throws and excellent ground technique. African junior champion working towards international competition.',
    profileUrl: 'https://example.com/kwame-mensah',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=60',
    currentPrice: 85,
    price24hChange: 4.5,
    price7dChange: 12.3,
    tradingVolume: 42000,
    holders: 156,
    tags: ['New'],
    priceHistory: generatePriceHistory(85),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '11',
    name: 'Anna Kowalski',
    symbol: 'AKOW',
    sport: 'Volleyball',
    category: 'Pro',
    nationality: 'Poland',
    team: 'Warsaw Volleyball',
    position: 'Outside Hitter',
    age: 27,
    height: '1.88m',
    bio: 'Powerful spiker with exceptional vertical jump. Polish national team member and European league star player.',
    profileUrl: 'https://example.com/anna-kowalski',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=25',
    currentPrice: 340,
    price24hChange: 2.9,
    price7dChange: 9.8,
    tradingVolume: 195000,
    holders: 478,
    tags: ['Featured'],
    priceHistory: generatePriceHistory(340),
    createdAt: new Date(Date.now() - 135 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '12',
    name: 'Raj Patel',
    symbol: 'RPAT',
    sport: 'Cricket',
    category: 'Semi-pro',
    nationality: 'India',
    team: 'Mumbai Strikers',
    position: 'Batsman',
    age: 22,
    height: '1.75m',
    bio: 'Talented batsman with aggressive stroke play. Rising through domestic cricket leagues with consistent high scores.',
    profileUrl: 'https://example.com/raj-patel',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=32',
    currentPrice: 165,
    price24hChange: 3.2,
    price7dChange: 7.8,
    tradingVolume: 88000,
    holders: 245,
    tags: [],
    priceHistory: generatePriceHistory(165),
    createdAt: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '13',
    name: 'Isabella Ferrari',
    symbol: 'IFER',
    sport: 'Cycling',
    category: 'Pro',
    nationality: 'Italy',
    team: 'Team Azzurra',
    position: 'Road Racing',
    age: 25,
    height: '1.68m',
    bio: 'Endurance cyclist with exceptional climbing ability. Multiple stage wins in international tours and Giro d\'Italia competitor.',
    profileUrl: 'https://example.com/isabella-ferrari',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=44',
    currentPrice: 275,
    price24hChange: 5.1,
    price7dChange: 14.6,
    tradingVolume: 148000,
    holders: 389,
    tags: ['Fast Growing'],
    priceHistory: generatePriceHistory(275),
    createdAt: new Date(Date.now() - 110 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '14',
    name: 'Liam O\'Brien',
    symbol: 'LOBR',
    sport: 'Rugby Sevens',
    category: 'Pro',
    nationality: 'Ireland',
    team: 'Leinster Rugby',
    position: 'Wing',
    age: 26,
    height: '1.82m',
    bio: 'Lightning-fast wing with try-scoring instincts. Irish national sevens team member and World Series competitor.',
    profileUrl: 'https://example.com/liam-obrien',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=11',
    currentPrice: 310,
    price24hChange: 4.7,
    price7dChange: 16.2,
    tradingVolume: 172000,
    holders: 423,
    tags: ['Featured'],
    priceHistory: generatePriceHistory(310),
    createdAt: new Date(Date.now() - 125 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '15',
    name: 'Min-jun Kim',
    symbol: 'MKIM',
    sport: 'Taekwondo',
    category: 'Elite',
    nationality: 'South Korea',
    team: 'Seoul Taekwondo',
    position: 'Under 68kg',
    age: 24,
    height: '1.76m',
    bio: 'Olympic champion with devastating head kicks and tactical brilliance. World champion and dominant force in international taekwondo.',
    profileUrl: 'https://example.com/minjun-kim',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=52',
    currentPrice: 720,
    price24hChange: 6.8,
    price7dChange: 19.4,
    tradingVolume: 410000,
    holders: 812,
    tags: ['Elite', 'Featured'],
    priceHistory: generatePriceHistory(720),
    createdAt: new Date(Date.now() - 190 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '16',
    name: 'Fatima Al-Rashid',
    symbol: 'FRAS',
    sport: 'Shooting',
    category: 'Semi-pro',
    nationality: 'UAE',
    team: 'Dubai Shooting',
    position: '10m Air Rifle',
    age: 21,
    height: '1.65m',
    bio: 'Precision shooter with exceptional focus and consistency. Asian championship medalist and Olympic qualifier.',
    profileUrl: 'https://example.com/fatima-alrashid',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=27',
    currentPrice: 142,
    price24hChange: 2.3,
    price7dChange: 6.9,
    tradingVolume: 71000,
    holders: 187,
    tags: ['New'],
    priceHistory: generatePriceHistory(142),
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '17',
    name: 'Lucas Santos',
    symbol: 'LSAN',
    sport: 'Rowing',
    category: 'Amateur',
    nationality: 'Brazil',
    team: 'Rio Rowing',
    position: 'Single Sculls',
    age: 19,
    height: '1.92m',
    bio: 'Powerful rower with excellent technique and endurance. South American junior champion with Olympic potential.',
    profileUrl: 'https://example.com/lucas-santos',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=14',
    currentPrice: 95,
    price24hChange: 6.2,
    price7dChange: 15.7,
    tradingVolume: 48000,
    holders: 168,
    tags: ['New', 'Fast Growing'],
    priceHistory: generatePriceHistory(95),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '18',
    name: 'Zara Hassan',
    symbol: 'ZHAS',
    sport: 'Badminton',
    category: 'Pro',
    nationality: 'Malaysia',
    team: 'KL Badminton',
    position: 'Singles',
    age: 23,
    height: '1.70m',
    bio: 'Agile badminton player with deceptive shot-making and court coverage. Multiple BWF tournament wins and top 20 world ranking.',
    profileUrl: 'https://example.com/zara-hassan',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=41',
    currentPrice: 235,
    price24hChange: 3.6,
    price7dChange: 11.2,
    tradingVolume: 128000,
    holders: 334,
    tags: [],
    priceHistory: generatePriceHistory(235),
    createdAt: new Date(Date.now() - 95 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '19',
    name: 'Andre Ivanov',
    symbol: 'AIVA',
    sport: 'Weightlifting',
    category: 'Semi-pro',
    nationality: 'Russia',
    team: 'Moscow Strength',
    position: 'Under 89kg',
    age: 25,
    height: '1.74m',
    bio: 'Powerful weightlifter with impressive clean and jerk technique. European championship competitor with consistent personal records.',
    profileUrl: 'https://example.com/andre-ivanov',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=53',
    currentPrice: 168,
    price24hChange: 1.9,
    price7dChange: 4.8,
    tradingVolume: 84000,
    holders: 212,
    tags: [],
    priceHistory: generatePriceHistory(168),
    createdAt: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: '20',
    name: 'Sarah Thompson',
    symbol: 'STHO',
    sport: 'eSports',
    category: 'Pro',
    nationality: 'Canada',
    team: 'Team Velocity',
    position: 'Support',
    age: 22,
    height: '1.68m',
    bio: 'Elite eSports player specializing in strategic team play. Multiple championship wins and recognized as one of the top support players globally.',
    profileUrl: 'https://example.com/sarah-thompson',
    highlightVideoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    imageUrl: 'https://i.pravatar.cc/300?img=38',
    currentPrice: 385,
    price24hChange: 8.9,
    price7dChange: 24.5,
    tradingVolume: 215000,
    holders: 623,
    tags: ['Featured', 'Fast Growing', 'Promoted'],
    priceHistory: generatePriceHistory(385),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString()
  }
];

export const initialNews: NewsItem[] = [
  {
    id: 'n1',
    title: 'Marco Silva Signs Extended Contract with FC Porto',
    summary: 'Portuguese midfielder Marco Silva has signed a three-year contract extension, solidifying his future with the club through 2027.',
    sport: 'Football',
    category: 'Career',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/marco-silva-contract',
    relatedAthleteSymbol: 'MSIL'
  },
  {
    id: 'n2',
    title: 'Yuki Tanaka Breaks National Record in 200m Freestyle',
    summary: 'Japanese swimmer Yuki Tanaka set a new national record at the World Championships qualifiers, finishing with a time of 1:44.23.',
    sport: 'Swimming',
    category: 'Performance',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/yuki-tanaka-record',
    relatedAthleteSymbol: 'YTAN'
  },
  {
    id: 'n3',
    title: 'Sofia Rodriguez Reaches Quarter-Finals at Madrid Open',
    summary: 'Spanish tennis star Sofia Rodriguez defeated the world number 8 to advance to the quarter-finals in a thrilling three-set match.',
    sport: 'Tennis',
    category: 'Performance',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/sofia-rodriguez-madrid',
    relatedAthleteSymbol: 'SROD'
  },
  {
    id: 'n4',
    title: 'NBA Scouts Watching James Mitchell in G League Playoffs',
    summary: 'Multiple NBA teams have sent scouts to watch point guard James Mitchell as he leads his G League team through the playoffs.',
    sport: 'Basketball',
    category: 'Transfer',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/james-mitchell-nba',
    relatedAthleteSymbol: 'JMIT'
  },
  {
    id: 'n5',
    title: 'Amara Okafor Qualifies for World Championships',
    summary: 'Nigerian sprinter Amara Okafor secured her spot at the World Championships with a stunning 9.98 second 100m performance.',
    sport: 'Athletics',
    category: 'Performance',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/amara-okafor-worlds',
    relatedAthleteSymbol: 'AOKA'
  },
  {
    id: 'n6',
    title: 'Emma Larsson Wins European Gymnastics Gold',
    summary: 'Swedish gymnast Emma Larsson captured gold in the all-around competition at the European Championships with a flawless performance.',
    sport: 'Gymnastics',
    category: 'Performance',
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/emma-larsson-gold',
    relatedAthleteSymbol: 'ELAR'
  },
  {
    id: 'n7',
    title: 'Min-jun Kim Defends Olympic Gold Medal',
    summary: 'South Korean taekwondo champion Min-jun Kim successfully defended his Olympic gold medal with dominant performances throughout the tournament.',
    sport: 'Taekwondo',
    category: 'Performance',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/minjun-kim-olympic-gold',
    relatedAthleteSymbol: 'MKIM'
  },
  {
    id: 'n8',
    title: 'Sarah Thompson Leads Team to eSports Championship Victory',
    summary: 'Canadian eSports pro Sarah Thompson was named tournament MVP as Team Velocity won the international championship.',
    sport: 'eSports',
    category: 'Performance',
    date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/sarah-thompson-championship',
    relatedAthleteSymbol: 'STHO'
  },
  {
    id: 'n9',
    title: 'International Olympic Committee Announces New Sports for 2028',
    summary: 'The IOC has confirmed the addition of several new sports to the 2028 Olympic Games, expanding opportunities for athletes worldwide.',
    sport: 'Others',
    category: 'Others',
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/ioc-2028-sports'
  },
  {
    id: 'n10',
    title: 'Global Sports Investment Reaches Record High',
    summary: 'A new report shows that sports-related investments have reached an all-time high, with digital platforms driving significant growth.',
    sport: 'Others',
    category: 'Others',
    date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/sports-investment-record'
  },
  {
    id: 'n11',
    title: 'Diego Mendez Announces Move to Professional Boxing',
    summary: 'Mexican boxer Diego Mendez will make his professional debut next month after an impressive semi-pro record.',
    sport: 'Boxing',
    category: 'Transfer',
    date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/diego-mendez-pro',
    relatedAthleteSymbol: 'DMEN'
  },
  {
    id: 'n12',
    title: 'Isabella Ferrari Wins Mountain Stage in Giro d\'Italia',
    summary: 'Italian cyclist Isabella Ferrari showcased her climbing prowess with a stage victory in the mountainous terrain of the Giro d\'Italia.',
    sport: 'Cycling',
    category: 'Performance',
    date: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    readMoreUrl: 'https://example.com/news/isabella-ferrari-giro',
    relatedAthleteSymbol: 'IFER'
  }
];
